modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory (32 is current forge version)
license="LGPL 3.0 License"

[[mods]] #mandatory
modId="mostructures" #mandatory
logoFile="icon.png"
version="1.2.0-1.16.5" #mandatory
displayName="Mo' Structures" #mandatory
authors="Frqnny" #optional
description='''
Mo' Structures is Fabric's best structure mod (NOW PORTED TO FORGE :)), carefully designed to enrich your world with many fun adventures to be had! Mo' Structures is carefully designed to bring interesting lore to your Minecraft World.  We focus on the RPG aspect of your world rather than an aesthetic one. This means we add Dungeons, Towers, Lore, and much more! Using loot tables, advancements, jigsaws, unused bosses in vanilla, and more, we are able to bring many new experiences that will make this mod be a must-download for every mod gameplay.
'''

# makes sure our mod does not be attempted to be ran on older version of Minecraft and explodes
[[dependencies.mostructures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17.0)"

[[dependencies.mostructures]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"